name: predict_liver_rejection_env
channels:
  - conda-forge
dependencies:
  - jupyter 
  - libxgboost = 2.1.1
  - matplotlib >= 3.8
  - openpyxl >= 3.0 # to read and write excel files 
  - pandas >= 2.0
  - pip >= 24.0
  - pyarrow # python lib for Apache arrow, to accelerate data processing ad analysis
  - py-xgboost = 2.1.1 # package for gradient descent 
  - python = 3.12
  - scikit-learn >= 1.4
  - statsmodels=0.14.5
  - xgboost = 2.1.1
  - pip:
      - seaborn == 0.13.2
